### ISSUE TITLE
Shell中发起的请求永远无法验证成功

### ISSUE THREAD

**Issue by chinamcafee** [JavaBaas/JavaBaasServer#7]
您好，感谢您开源JavaBaas
学习了一下源代码，发现在Shell中对AdminSign的加密代码是DigestUtils.md5DigestAsHex((propertiesUtil.getKey() + ":" + timestamp).getBytes());
但是在Server中的校验代码是：
DigestUtils.md5DigestAsHex((key + ":" + timeStamp + ":" + nonce).getBytes());
多了一个":"+nonce，不是很清楚这个nonce的用途是什么？
但是这样肯定算出来的两个MD5码是不一样的，永远通过校验不了。

**Comment by codi** [comment]
非常感谢你对JavaBaas的支持～
nonce是server最新代码中针对防重放攻击增加的安全参数，每次请求需要生成一个唯一的nonce，重复nonce的请求将被拒绝。
由于shell工具尚未更新，因此shell工具与server最新版已经无法配合使用，稍后会更新最新版本shell工具。如果需要使用shell，请使用server release1.0.0版本。
感谢您提出的宝贵意见，JavaBaas还会持续不断的维护与更新。

**Comment by chinamcafee** [comment]
明白了，非常感谢您的耐心解答，预祝JavBaas越来越好
